name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Step 3: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # Step 4: Initialize Terraform
    - name: Terraform Init
      run: terraform init

  


    # Step 7: Terraform Plan
    - name: Terraform Pla
      run: terraform plan 

    # Step 8: Terraform Apply (only on push to main)
    - name: Terraform Apply
      run: terraform apply -auto-approve
